# Generated by Django 3.1.2 on 2020-10-16 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameroom', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameSession',
        ),
    ]
