# Generated by Django 3.1.2 on 2020-10-13 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameroom', '0002_profile_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='GameSession',
        ),
    ]
